### ISSUE TITLE
Uploaded images

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/product#1]
![ea8c_rocket_surgeon](https://cloud.githubusercontent.com/assets/149811/7688672/6a9f64c0-fd74-11e4-8a68-b216583daf31.jpg)

**Comment by aaronschachter** [comment]
<img width="852" alt="screen shot 2016-10-26 at 7 04 47 am" src="https://cloud.githubusercontent.com/assets/1236811/19730271/7db27178-9b4e-11e6-97d6-b16659b13532.png">

**Comment by aaronschachter** [comment]
<img width="965" alt="activity-2 0" src="https://cloud.githubusercontent.com/assets/1236811/19916543/1c5d8e42-a078-11e6-82fb-06c3487bae52.png">
