### ISSUE TITLE
Can we combine the Campaign Detail and Group screens?

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#10]
It seems confusing to have the two different views of a Campaign which are accessed via different ways.

Per current version of Spidermap: https://github.com/DoSomething/product/blob/master/LetsDoThis/SpiderMap.jpg
- Campaign Detail is accessed from the Main Feed
- Campaign Detail is accessed from the Campaign image and Title in your Hub
- Group page is only accessed by the number and arrow within the row of avatars

I would not expect a different view in the 3rd scenario. 

Proposal:
Use Campaign Detail page, with 2 additional sections if user is in a group:
- Avatars 
- "Friends Doing it" reportbacks, which display like the regular "People Doing it" reportbacks.

**Comment by marahml** [comment]
@aaronschachter the point of scenario 3 is that it's its own page entirely - for you and your friends. 

Eventually we would host invite-triggered rewards and videos there as well. 

I think users would actually be more confused if only 1 small thing changed when they went to that screen. We don't want to make them have to work to figure out what the difference is.
