### ISSUE TITLE
Reportback Item screen does not link to Campaign screen

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#12]
Refs "What if i want to do this" question in the Reportback Item screen.

No link to the Campaign to view the Campaign Detail page. Simply a pic, caption, quantity but no way to sign up for the campaign from that view.

If one wanted to, they'd need to hit the back button and find the campaign through the Main Feed tab (it should appear above)

Functionally this works, however I think UX may be improved if we add a link to the Campaign Detail screen, to avoid hitting the back button and scrolling/searching.

**Comment by marahml** [comment]
yep totally. this was supposed to be in original designs but was missed. @lkpttn added to rb screen designs and uploaded to the repo. thanks @aaronschachter!

**Comment by lkpttn** [comment]
Closed
