### ISSUE TITLE
Add "change photo" option to Reportback Submit View

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#13]
Refs "Change photo or take" comment in Spiderman map

In Reportback Submit screen, add an icon/button which presents the same Action Sheet (Use Existing photo / Take picture), allowing user to change the reportback image until it's been submitted.

**Comment by lkpttn** [comment]
This has been added in one of the recent commits. Need to learn how to close out issues with PRs.

**Comment by aaronschachter** [comment]
https://help.github.com/articles/closing-issues-via-commit-messages/
