### ISSUE TITLE
Offline functionality

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#16]
Need spec on what (if anything) is available if there is no network available.

Things you can't do without a connection:
- Signup for a campaign
- Reportback for a campaign

**Comment by jonuy** [comment]
Things available when offline:
- user profile: campaign activities, own reportback pictures, 
- campaign details

Things not available when offline:
- submitting signup for a campaign
- submitting reportback for a campaign
- group reportback gallery
- public campaign reportback galleries
- submitting kudos
- user registration and login

**Comment by aaronschachter** [comment]
The Invite screen won't have any use at all offline.

Suggested treatments:
- Keep the screen the same, but with a message that displays Connectivity error. Buttons don't do anything.
  OR
- Fail whale style image to replace the Invite screen

**Comment by aaronschachter** [comment]
Per recent convo's with the team, first version of the app will not support any functionality offline. We'll display a fail whale type screen if connection is lost, regardless of what screen the User is viewing.

cc @marahml @jonuy @lkpttn
