### ISSUE TITLE
How much do we store into app memory?

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#17]
- [ ] Campaign details
- [ ] Campaign/Interest Group gallery
- [ ] Current user details/activity
- [ ] Public user details/activity. 

Big questions here are mainly around images.

**Comment by aaronschachter** [comment]
@jonuy Seems like we don't need to store anything if we aren't supporting offline?

**Comment by marahml** [comment]
@aaronschachter yes indeed - we have nixed offline mode.
