### ISSUE TITLE
Logout copy

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#19]
I would advise we have a prompt "Are you sure?". But let's just specify exactly what that copy should say.  Currently reads in iOS as:

![screen shot 2015-06-23 at 9 49 57 am](https://cloud.githubusercontent.com/assets/1236811/8307684/f5426afc-198d-11e5-886c-0d942804bd3a.png)

**Comment by lkpttn** [comment]
Yeah, this is a good idea. +1

**Comment by aaronschachter** [comment]
Sweet! we just need finalized copy...

**Comment by marahml** [comment]
Let's just use copy above pls. That works and is aligned with our tone.

**Comment by marahml** [comment]
Added final copy here: https://docs.google.com/document/d/1FDGYQ2rqDpBgl8Octow9-1yKMdxzXqaQSSxnoVDz6M0/edit#
