### ISSUE TITLE
Missing user image on FB Connect screen

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#26]
Assume we want to pull the FB proflie pic?  Should we replace the FB icon here with the user profile photo?

**Comment by marahml** [comment]
+1 

@jonuy can we include in the permissions we get from FB?

**Comment by marahml** [comment]
following up here @jonuy 

also @lkpttn mind throwing up a new design visual for this? 

thanks!

**Comment by lkpttn** [comment]
Done, fixed in 
https://github.com/DoSomething/product/commit/ed027cfe26f1532459526440036bc74e134c9d8b
