### ISSUE TITLE
Date picker for registration?

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#31]
@lkpttn  - We discussed in Slack using a date picker, i'm wondering if it's easier for the user to just type in their birthday (instead of scrolling to the right year).

cc @marahml 

I believe Android app currently just has the user input the year as MM DD YYYY?

**Comment by lkpttn** [comment]
Does this make the code any easier to deal with? The UX preference is to use the date picker since that's what get presented in other apps, web, etc.

**Comment by aaronschachter** [comment]
I already have date picker in place, so that's not really an issue.  The birthdate is defaulting to the current date, which is annoying, because you always have to scroll back to 1950 or whatever.  Any suggestions for a default year, @lkpttn ?

**Comment by lkpttn** [comment]
1995?

**Comment by marahml** [comment]
I'd prefer users just entering the date. much quicker and easier.

**Comment by aaronschachter** [comment]
So the user would actually need to select the `/` key from the keyboard in order to format the date correctly? Would be useful to see how Touchlab has implemented this, as I know they don't have a date picker.

**Comment by aaronschachter** [comment]
Going through the Facebook app registration process to see how they handle. They use a date picker (and interestingly, default to current date):

![they say its your birthday](https://cloud.githubusercontent.com/assets/1236811/8562724/69218e14-24ea-11e5-9560-f8dd4d79bc37.png)

**Comment by lkpttn** [comment]
I like this implementation. Is this the normal UIDatePicker or a custom job?

**Comment by aaronschachter** [comment]
This is just a normal `UIDatePicker`. I like using a dropdown as the main field though.. currently I have it set as a `UITextField` but that allows a user to type a bogus value into the date field.

**Comment by lkpttn** [comment]
I say roll with the dropdown. Data protection and such.

**Comment by aaronschachter** [comment]
Yes that'd be the plan. I thought it was interesting that FB defaults to the current date for birthdate. I suppose I can just leave that... i guess it's not as annoying when for a User since they only use the form the one single time to register.

**Comment by aaronschachter** [comment]
Per this thread I am keeping the date picker on iOS, and keeping default date as today.
