### ISSUE TITLE
Validation for mobile number

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#32]
We need some sort of validation here (can't let a user enter just 3 numbers for a mobile number)

What should the rules be?

@lkpttn @marahml

**Comment by marahml** [comment]
I'd like for us to be able to validate US and international phone numbers.

Can you check out this library? It might help. https://github.com/googlei18n/libphonenumber

**Comment by aaronschachter** [comment]
Nice find, @marahml . Looks like there is a Cocoapod for it too, which is good news: http://cocoadocs.org/docsets/libPhoneNumber-iOS/0.5.7/

Should we add this into the spec for what needs to be shipped for a v1.0?

**Comment by DFurnes** [comment]
Smart. Looks like there's a [version for PHP](https://github.com/giggsey/libphonenumber-for-php) as well.

**Comment by aaronschachter** [comment]
For the iOS app, not worrying about dashes/formatting, so just using a min of 7 digits and max of 15 per Stackoverflow threads.
