### ISSUE TITLE
How to handle multiple errors in registration

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#33]
Per https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Onboarding/DS%20Sign%20In%20Error*.png

What if there are multiple errors on the registration form? How does this look?

e.g. User does not provide a valid email, mobile and last name. If these messages should appear inline (instead of as a big long message in the banner), please mock up how this should look.

cc @marahml

**Comment by marahml** [comment]
@lkpttn fields that are incorrect / have errors should all appear red, and error message should bullet point each issue please

**Comment by marahml** [comment]
Closing unless there are any other Qs on this
