### ISSUE TITLE
Facebook connect -- password

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#34]
Should this read something like "Confirm your Facebook details and choose a DoSomething.org password" ?

https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Onboarding/FB%20Connect*.png

I don't think we can access the User's Facebook password to populate the field with a default value, so the User will need to enter a password for their new DoSomething account.

Just to be clear/document: we are not implementing Facebook connect, so a user isn't actually able to login with their Facebook account.

cc @marahml  @lkpttn

**Comment by marahml** [comment]
"Confirm your Facebook details and set your password"
