### ISSUE TITLE
Can't open source app repositories

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#36]
Both the Android and iOS builds require the Brandon custom font to exist in the repositories, which is why each repo has been set to private.

https://github.com/DoSomething/LetsDoThis-Android/tree/master/app/src/main/assets/fonts
https://github.com/DoSomething/LetsDoThis-iOS/commit/5fabcf6b7600550255d107efd2cf0d6af7a35b18

This isn't a blocker, but documenting here to let @mshmsh5000 know what's going on if/when he's wondering why they've been made private. We should be doing the same for https://github.com/DoSomething/neue ?

One quick win to resolve this would be finding a different font that would be legal to keep in the repositories.   

If keeping the repo's private is not an issue, then let's do this (er, close this)

**Comment by aaronschachter** [comment]
I'm liking the idea of removing the font files from the build, and just keeping them untracked... @jonuy @mshmsh5000

**Comment by jonuy** [comment]
I'm not opposed to that.

**Comment by aaronschachter** [comment]
Is this doable on the android side as well? I (or someone else) can give it a shot soon on iOS

**Comment by jonuy** [comment]
Yea, we already .gitignore a secrets.xml file. We can similarly do this for the font files.

**Comment by mshmsh5000** [comment]
:+1: :exclamation:

**Comment by jonuy** [comment]
The [Android](https://help.github.com/articles/remove-sensitive-data/) repo is now public again.

**Comment by mshmsh5000** [comment]
Fast work! :beers:

**Comment by aaronschachter** [comment]
Handled via .gitignore
