### ISSUE TITLE
Facebook Connect - access to Profile photo

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#41]
Refs comment here: https://github.com/DoSomething/product/issues/26#issuecomment-117229033

Are we able to access Profile photo with current FB setup?

**Comment by jonuy** [comment]
Yea, it looks like the pic is included under the `public_profile` permission that's granted by default.

![fb_permissions](https://cloud.githubusercontent.com/assets/696595/8653657/823ec0b6-2953-11e5-931f-128e4133ebfa.png)
