### ISSUE TITLE
what order should the interest groups appear in?

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#46]
https://github.com/DoSomething/api/wiki/Mobile-App-Usage#query-for-campaigns-by-interest-group

**Comment by marahml** [comment]
what's the simplest solution for build time?

**Comment by jonuy** [comment]
As long as interest group ordering (and naming) stays the same from month to month, there shouldn't be an affect on build time.

**Comment by aaronschachter** [comment]
Right, @marahml this issue is simply to list what order those term names should appear when displayed in the tabs. It's hardcoded, so tweaks to it require dev time + new build/release

**Comment by marahml** [comment]
In terms of a strategic decision - its hard to know what will perform best and what we will need to put in front of users first. 

But I'd guesstimate that this is a good order to start with: 
artsy     1302
bro    1300
fem   1301
social 1303

**Comment by aaronschachter** [comment]
ok!
