### ISSUE TITLE
Need flow for if user forgets password

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#5]
Standard behavior is another screen where user inputs their email address, with confirmation language something like "If there is an account registered with that email, instructions have been sent."

**Comment by marahml** [comment]
also Trello card here: https://trello.com/c/kTGtLSyt/136-design-forgot-password-screens

**Comment by marahml** [comment]
@lkpttn let me know if you need help w these screens!

I'd be happy if it mirrored the web forgot pw flow for now.

**Comment by marahml** [comment]
@lkpttn can you just add a forgot pw link to registration screens? that would push to the site flow

**Comment by lkpttn** [comment]
Yeah, sorry these are already in.
