### ISSUE TITLE
Need approved copy: justification for asking user for location

### ISSUE THREAD

**Issue by tongxiang** [DoSomething/product#57]
When the user enters the user registration flow, she'll see a popup asking her to allow the app to use her location while she uses the app. (See #44). 

![Image of access location query](http://cdn4.raywenderlich.com/wp-content/uploads/2014/10/Screen-Shot-2014-10-08-at-11.42.46-AM-179x320.png)

The non-bolded copy above is changeable by us. What copy would be best here?

**Comment by lkpttn** [comment]
@tongxiang We're going to use this screen (right after signing up/signing in) to explain why we want to have access to these things. I need to update it for location and the removal of friends.

https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Onboarding/Notification%20Priming*.png

**Comment by tongxiang** [comment]
In that case, for the popup, I'll just duplicate the copy you update that screen with.

**Comment by marahml** [comment]
@tongxiang this is good to close yah?

**Comment by tongxiang** [comment]
Right now, we're using: 

"We need your location to give you the most relevant campaigns!"

We were concerned before because this wasn't actually true; i.e. the user's location doesn't actually fine-tune the campaign selection. 

But happy to run with this for now, unless anyone objects.
