### ISSUE TITLE
Hub treatment for data in Doing but nothing Completed

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#6]
Refs https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Hub/Hub%20Empty*.png

What does the "Been there, Done that" section of the Hub look like if I've signed up for a campaign(s) but have not completed?  Is it hidden?  Or is there a message that should be displayed?

**Comment by marahml** [comment]
@aaronschachter hidden pls! goal of the hub is to focus on things you're doing right then and there. "Been there, done good" is a bonus section that should just show up after you do something.

**Comment by aaronschachter** [comment]
Sweet
