### ISSUE TITLE
Lets Do This - Privacy Policy

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#63]
There's no way to view the privacy policy I'm agreeing to when I register.

**Comment by tongxiang** [comment]
Will be handled by #475.

**Comment by marahml** [comment]
@lkpttn can we add this to the designs for registration pls? should link to the site privacy policy

**Comment by lkpttn** [comment]
I don't think this should still be open, the corresponding issue was closed in the Let's Do This repo

**Comment by tongxiang** [comment]
Yup, closed by [this issue on iOS](https://github.com/DoSomething/LetsDoThis-iOS/pull/487).
