### ISSUE TITLE
Nami Images Issue

### ISSUE THREAD

**Issue by namimody** [DoSomething/product#66]
![image](https://cloud.githubusercontent.com/assets/12396076/11749936/94471a0c-9ffe-11e5-9997-c4b6a882f65a.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/11754277/2da7fb3a-a018-11e5-8eb6-712476414647.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/11754739/481d2ffa-a01b-11e5-8170-ab607ec3ce60.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/11755087/e3ed7cbc-a01d-11e5-8b33-369f2e93ccda.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17084820/3aef9fd4-5196-11e6-8517-47c403da2bc1.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17084846/b08710c4-5196-11e6-8474-e8023081b5fd.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17084906/0329b57e-5198-11e6-9583-7fb4cffe607a.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17084924/a3ff1066-5198-11e6-873c-bee00031330a.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17084930/d8c25cea-5198-11e6-8965-ecd7bd07aa8a.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17085009/59c24182-519b-11e6-977e-581e845056d5.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17085377/4c808ffc-51a4-11e6-9255-22143fb58875.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17086030/aad0f59a-51b5-11e6-985e-98d7fc51faa0.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17086286/c80c0388-51bb-11e6-8219-0bc2dcfbf850.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17087248/a538d076-51d3-11e6-9c91-d5da74f4b062.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17087416/4343dc36-51d7-11e6-9db0-0db95321048d.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17102487/d2d8154a-5247-11e6-8ff4-fcf452bced8f.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17102497/dbcb8484-5247-11e6-8cdf-33b7338e7283.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17102542/145bfbee-5248-11e6-9438-3c8f205ca246.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17147783/3c965f74-5332-11e6-86f5-c30280c74190.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17153388/8e074b26-534a-11e6-91a2-8e0bd6153e2a.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17153902/c294ec0c-534c-11e6-9357-35d17e653083.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17154214/00e78a90-534e-11e6-93ec-ab7acf218475.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17155689/318145aa-5354-11e6-8543-d04e659e7d84.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17155840/d3042b90-5354-11e6-8076-1d13f768dcdb.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17178814/e77d627c-53e4-11e6-9b38-31af388a6d30.png)

**Comment by namimody** [comment]
![image](https://cloud.githubusercontent.com/assets/12396076/17179214/5ff53558-53e6-11e6-93f6-c073e56e51f5.png)

**Comment by aaronschachter** [comment]
<img width="1104" alt="screen shot 2017-02-21 at 10 39 40 am" src="https://cloud.githubusercontent.com/assets/1236811/23179899/6044973c-f824-11e6-8ec0-6c69000ffcd5.png">

**Comment by aaronschachter** [comment]
<img width="892" alt="screen shot 2017-02-16 at 7 33 45 am" src="https://cloud.githubusercontent.com/assets/1236811/23180327/f04b57ca-f825-11e6-9e60-34d3c93d1cc8.png">

**Comment by aaronschachter** [comment]
<img width="1440" alt="screen shot 2017-02-08 at 8 57 21 am" src="https://cloud.githubusercontent.com/assets/1236811/23181220/02437018-f829-11e6-91b1-9b8380f462c2.png">
<img width="1107" alt="screen shot 2017-02-21 at 11 29 58 am" src="https://cloud.githubusercontent.com/assets/1236811/23181245/1cf9c20e-f829-11e6-9fd8-e19f14193653.png">

**Comment by aaronschachter** [comment]
<img width="1012" alt="screen shot 2017-03-16 at 7 52 53 am" src="https://cloud.githubusercontent.com/assets/1236811/24002302/9e8ebd0a-0a1d-11e7-9e14-4b9b91ce3d20.png">

**Comment by aaronschachter** [comment]
<img width="724" alt="screen shot 2017-03-20 at 8 02 31 am" src="https://cloud.githubusercontent.com/assets/1236811/24105928/b76e8804-0d43-11e7-87f3-aeafa327ba9a.png">

<img width="1078" alt="screen shot 2017-03-20 at 8 04 10 am" src="https://cloud.githubusercontent.com/assets/1236811/24105965/d64bb6b6-0d43-11e7-9bac-6073d8d7b6b4.png">

**Comment by aaronschachter** [comment]
HI NAMI
<img width="638" alt="screen shot 2017-03-31 at 7 27 33 pm" src="https://cloud.githubusercontent.com/assets/1236811/24574482/49c52bb0-1648-11e7-93e0-94786e789a5d.png">

**Comment by aaronschachter** [comment]
<img width="1079" alt="screen shot 2017-03-31 at 8 23 45 pm" src="https://cloud.githubusercontent.com/assets/1236811/24575581/fd06d500-165e-11e7-9ca3-d5fbe6b45e6d.png">

**Comment by aaronschachter** [comment]
<img width="1010" alt="screen shot 2017-03-31 at 8 23 59 pm" src="https://cloud.githubusercontent.com/assets/1236811/24575602/869bab56-165f-11e7-90cb-108348d44c2a.png">

**Comment by aaronschachter** [comment]
<img width="1273" alt="screen shot 2017-04-10 at 3 56 29 pm" src="https://cloud.githubusercontent.com/assets/1236811/24885987/8df153de-1e06-11e7-9fda-495783d466de.png">

**Comment by aaronschachter** [comment]
![flowchart-gambit-architecture](https://cloud.githubusercontent.com/assets/1236811/26091362/914c70f2-39bf-11e7-95f0-8e49f15e5a20.png)

**Comment by aaronschachter** [comment]
![flowchart-gambit-request](https://cloud.githubusercontent.com/assets/1236811/26090808/13902bd4-39bc-11e7-8b91-44e0994372c8.png)

**Comment by aaronschachter** [comment]
<img width="1342" alt="screen shot 2017-06-26 at 11 48 17 am" src="https://user-images.githubusercontent.com/1236811/27555069-6ddfa226-5a65-11e7-8e0a-4f4a52ab179c.png">

**Comment by aaronschachter** [comment]
![slothierequest](https://user-images.githubusercontent.com/1236811/27874895-21023bf0-6166-11e7-8abd-40c92b79b91b.png)

**Comment by aaronschachter** [comment]
![slothbot-diagram](https://user-images.githubusercontent.com/1236811/28039510-79c8b6a0-6577-11e7-9da1-19a4bc8f5952.png)

**Comment by aaronschachter** [comment]
<img width="556" alt="screen shot 2017-07-11 at 9 58 18 am" src="https://user-images.githubusercontent.com/1236811/28080095-9194e2b0-661f-11e7-9e1c-8250a6bc064c.png">

**Comment by aaronschachter** [comment]
![send-message-support](https://user-images.githubusercontent.com/1236811/29533885-b639862a-8668-11e7-8ad1-0a6259ef8af8.png)
