### ISSUE TITLE
How should campaigns be sorted?

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#7]
Need details for:
- Main Feed
- User Doing
- User Completed

**Comment by marahml** [comment]
- Main Feed 
  -- Alphabetical would be fine
  -- Open to other ideas
- User Doing 
  -- Order in which user signed up for campaign (top being most recent)
- User Completed
  -- Order in which user completed the campaign (top being most recent)

**Comment by aaronschachter** [comment]
@marahml Will all campaigns expire at the same time? If not, the end date could be a nominee for the order of "User Doing"

ABC is fine here too, if no one has other thoughts, let's do that to close this out.

**Comment by lkpttn** [comment]
All the campaigns end at the same time, like 11:59 March 31. +1 to alphabetical sorting.

**Comment by aaronschachter** [comment]
ABC its easy as 123
