### ISSUE TITLE
Treatment of Campaign Detail / Feed when user has reported back

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/product#8]
Refs: https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Discovery/Campaign%20Detail*.png

Also, for the main feed.

**Comment by lkpttn** [comment]
This is what happens to the main feed after a campaign is expired: https://github.com/DoSomething/product/blob/master/LetsDoThis/Screens/Discovery/Main%20Feed%20Expired.png

There shouldn't be a way to access the campaign detail page once it's expired. Someone could be sitting on the detail page when it expires and then tries to report back, in which case we need to give them an error.

**Comment by aaronschachter** [comment]
@lkpttn Renamed this to make it more clear. instead of "stop being bored" and "prove it" -- What does the button say after you've proved it?

**Comment by aaronschachter** [comment]
Closed by #9. Button labels post-sign up are "Prove it" and "Proved it".
